grails-app/controllers/com/confspot/LoginController.groovy
package com.confspot

import org.springframework.security.web.savedrequest.DefaultSavedRequest
import twitter4j.TwitterFactory
import twitter4j.conf.ConfigurationBuilder
import twitter4j.Twitter
import twitter4j.ProfileImage

class LoginController {

    def springSecurityService
    def grailsApplication

    def twitterAuth = {
        def config = grailsApplication.config.twitter
        def configurationBuilder = new ConfigurationBuilder()
        configurationBuilder.with {
            debugEnabled = true
            OAuthConsumerKey = config.key
            OAuthConsumerSecret = config.secret
        }
        def twitterFactory = new TwitterFactory(configurationBuilder.build())
        def twitter = twitterFactory.getInstance()

        def requestToken = twitter.getOAuthRequestToken(createLink(action: 'twitterCallback', absolute: true))
        session.twitterToken = requestToken
        session.twitter = twitter
        redirect url: requestToken.authenticationURL

    }

    def twitterCallback = {
        def requestToken = session.twitterToken
        Twitter twitter = session.twitter

        def accessToken = twitter.getOAuthAccessToken(requestToken, params.oauth_verifier)

        def user = User.findByTwitterId(accessToken.userId)
        if (!user) {
            User.withTransaction {
                user = new User(username: accessToken.screenName, twitterId: accessToken.userId, enabled: true)
                user.save(failOnError: true)

                UserRole.create(user, Role.findByAuthority('ROLE_ORGANIZER'))
            }
        }

        def profileImage = twitter.getProfileImage(user.username, ProfileImage.MINI)
        session.profileImage = profileImage.URL

        springSecurityService.reauthenticate(user.username)

        DefaultSavedRequest url = session['SPRING_SECURITY_SAVED_REQUEST_KEY']
        if (url) {
            redirect url: url.redirectUrl
        } else {
            redirect uri: '/'
        }


    }
}

grails-app/views/layouts/_footer.gsp
<footer>
    <div class="container">
        <div class="row">
            <div class="span3">
                <h4>ConfSpot.com</h4>
                <ul>
                    <li><g:link uri="/"><g:message code="layout.home" /></g:link></li>
                    <li><g:link controller="conference" action="create"><g:message code="layout.signUpYourConference" /></g:link></li>
               </ul>
            </div>
            <div class="span3">
                <h4><g:message code="footer.contactUs" /></h4>
                <address>
                    <strong><g:message code="footer.confSpotTeam" /></strong><br>
                    <g:message code="footer.confSpotAddress" /><br/>
                    <a href="mailto:grails48@salenda.es">grails48@salenda.es</a>
                </address>
            </div>
            <div class="span4">
                <h4><g:message code="footer.aboutConfSpot" /></h4>
                <p><g:message code="footer.aboutConfSpot.text" /></p>
            </div>
            <div class="span2 social">
                <h4>Social</h4>
                <div class="row-fluid">
                    <div class="pull-left"><a class="btn btn-small" href="http://twitter.com/confspot"><i class="icon-large icon-twitter"></i></a></div>
                </div>
            </div>
        </div>
    </div>
</footer>

<%@page import="org.springframework.web.servlet.support.RequestContextUtils" %>
<g:if test="${RequestContextUtils.getLocale(request).language != 'en'}">
    <script type="text/javascript" src="${resource(plugin: 'jquery-ui', file: "js/jquery/i18n/jquery.ui.datepicker-${RequestContextUtils.getLocale(request).language}.js")}"></script>
</g:if>

<script type="text/javascript">

    var _gaq = _gaq || [];
    _gaq.push(['_setAccount', 'UA-36252382-1']);
    _gaq.push(['_trackPageview']);

    (function() {
        var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
        ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
        var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
    })();

</script>

grails-app/views/layouts/_navbar.gsp
<div class="navbar navbar-inverse navbar-fixed-top">
    <div class="navbar-inner">
        <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        </a>
        <g:link uri="/" class="brand logo">
            <r:img file="confspot.png" />
            ConfSpot.com
        </g:link>
        <div class="nav-collapse">
            <ul class="nav">
                <li><g:link controller="conference" action="create"><g:message code="layout.signUpYourConference" /></g:link></li>
            </ul>

            <%-- Search box --%>
			<form id="search-box" class="navbar-search pull-left" action="${createLink(mapping:'searchConferences')}" method="get">
				<input type="text" name="text" class="search-query span2" placeholder="${message(code:'conference.search')}">
			</form>
            
            <ul class="nav pull-right">
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                    	<span id="specificCountry" style="display:${session.position?.country?.name ? 'inline' : 'none'}">
	                    	<g:message code="layout.main.location"/> <span id="countryName">${session.position?.country?.name}</span>
	                    </span>
	                    <span id="allCountries" style="display:${!(session.position?.country?.name) ? 'inline' : 'none'}">
	                    	<g:message code="layout.main.allEvents" />
	                    </span>
                   	</a>
                </li>
                <li class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                        <g:message code="lang" />
                        <span class="caret"></span>
                    </a>
                    <ul class="dropdown-menu">
                        <li>
                            <render:langSwitch lang="es"/>
                        </li>
                        <li>
                            <render:langSwitch lang="en"/>
                        </li>
                    </ul>

                </li>
                <sec:ifNotLoggedIn>
                    <li>
                        <g:link controller="login" action="twitterAuth">
                            <i class="icon-twitter icon-white" data-original-title="icon-twitter" style="font-size: 18px;"></i>
                            <g:message code="layout.main.login" />
                        </g:link>
                    </li>
                </sec:ifNotLoggedIn>
                <sec:ifLoggedIn>
                    <li><g:link mapping="myConferences"><img src="${session.profileImage}" /> <sec:username/></g:link></li>
                    <li>
                        <g:link controller="logout">
                            <g:message code="layout.main.logout" />
                        </g:link>
                    </li>
                </sec:ifLoggedIn>
            </ul>
        </div>
    </div>
</div>
<div class="navbar-spacer"></div>

grails-app/views/layouts/main.gsp
<!DOCTYPE html>
<!--[if lt IE 7 ]> <html lang="en" class="no-js ie6"> <![endif]-->
<!--[if IE 7 ]>    <html lang="en" class="no-js ie7"> <![endif]-->
<!--[if IE 8 ]>    <html lang="en" class="no-js ie8"> <![endif]-->
<!--[if IE 9 ]>    <html lang="en" class="no-js ie9"> <![endif]-->
<!--[if (gt IE 9)|!(IE)]><!--> <html lang="en" class="no-js"><!--<![endif]-->
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
		<title><g:layoutTitle default="ConfSpot"/></title>
        <link rel="shortcut icon" href="${resource(file: '/images/favicon.ico')}">
		<g:layoutHead/>
		<r:require module="core"/>
        <link href='http://fonts.googleapis.com/css?family=Montserrat' rel='stylesheet' type='text/css'>
        <r:layoutResources />
	</head>
	<body>
        <g:render template="/layouts/navbar" />
		<g:layoutBody/>
        <g:render template="/layouts/footer" />
        <r:layoutResources />
	</body>
</html>